### ISSUE TITLE
"docker-compose" needs up-to-date

### ISSUE THREAD

**Issue by k4taya** [y-ohgi/introduction-docker#3]
because of [docker-compose.yml changes](https://github.com/y-ohgi/2019-aws-handson/commit/bcc717e8cd6280c38320ddef1a661bb7626bfbb0#diff-4e5e90c6228fd48698d074241c2ba760), it seems some diffs between codes in introduction and "2019-aws-handson" repo now.

In particular, the port number of nginx has been changed from 8080 to 8001, so it needs to be reflected all of document.

Otherwise, because these codes are just example, let visitors execute `docker ps`, reference PORTS of **2019-aws-handson_nginx** , then access http://localhost:port.

**Comment by y-ohgi** [comment]
thank you !!

https://github.com/y-ohgi/introduction-docker/commit/45e97f5e218fec1d69278531880fa2e50afffaaa
