### ISSUE TITLE
About Google analytics

### ISSUE THREAD

**Issue by peaceiris** [y-ohgi/introduction-docker#4]
https://github.com/y-ohgi/introduction-docker/commit/6c4cc218862cb5c1b8f3692e271f87047cf929ea

Google analytics を設置するのであれば、利用していることについて言及するプライバシーポリシーのページを用意した方が良いと思います。

**Comment by y-ohgi** [comment]
ありがとうございます！追加しました 🙇 

https://github.com/y-ohgi/introduction-docker/commit/67f66fd10fc078e341b4926d891ebd63ac30cc6b

**Comment by peaceiris** [comment]
👍
